/// Catálogo oficial CUT Chile.
const List<Map<String, String>> kClNivel1 = <Map<String, String>>[
  {'id': '01', 'nombre': 'Tarapacá'},
  {'id': '02', 'nombre': 'Antofagasta'},
  {'id': '03', 'nombre': 'Atacama'},
  {'id': '04', 'nombre': 'Coquimbo'},
  {'id': '05', 'nombre': 'Valparaíso'},
  {'id': '06', 'nombre': 'Libertador General Bernardo O\'higgins'},
  {'id': '07', 'nombre': 'Maule'},
  {'id': '08', 'nombre': 'Biobío'},
  {'id': '09', 'nombre': 'La Araucanía'},
  {'id': '10', 'nombre': 'Los Lagos'},
  {'id': '11', 'nombre': 'Aysén del General Carlos Ibáñez del Campo'},
  {'id': '12', 'nombre': 'Magallanes y de la Antártica Chilena'},
  {'id': '13', 'nombre': 'Metropolitana de Santiago'},
  {'id': '14', 'nombre': 'Los Ríos'},
  {'id': '15', 'nombre': 'Arica y Parinacota'},
  {'id': '16', 'nombre': 'Ñuble'},
];

const List<Map<String, String>> kClNivel2 = <Map<String, String>>[
  {'id': '011', 'nombre': 'Iquique', 'padre': '01'},
  {'id': '014', 'nombre': 'Tamarugal', 'padre': '01'},
  {'id': '021', 'nombre': 'Antofagasta', 'padre': '02'},
  {'id': '022', 'nombre': 'El Loa', 'padre': '02'},
  {'id': '023', 'nombre': 'Tocopilla', 'padre': '02'},
  {'id': '031', 'nombre': 'Copiapó', 'padre': '03'},
  {'id': '032', 'nombre': 'Chañaral', 'padre': '03'},
  {'id': '033', 'nombre': 'Huasco', 'padre': '03'},
  {'id': '041', 'nombre': 'Elqui', 'padre': '04'},
  {'id': '042', 'nombre': 'Choapa', 'padre': '04'},
  {'id': '043', 'nombre': 'Limarí', 'padre': '04'},
  {'id': '051', 'nombre': 'Valparaíso', 'padre': '05'},
  {'id': '052', 'nombre': 'Isla de Pascua', 'padre': '05'},
  {'id': '053', 'nombre': 'Los Andes', 'padre': '05'},
  {'id': '054', 'nombre': 'Petorca', 'padre': '05'},
  {'id': '055', 'nombre': 'Quillota', 'padre': '05'},
  {'id': '056', 'nombre': 'San Antonio', 'padre': '05'},
  {'id': '057', 'nombre': 'San Felipe de Aconcagua', 'padre': '05'},
  {'id': '058', 'nombre': 'Marga Marga', 'padre': '05'},
  {'id': '061', 'nombre': 'Cachapoal', 'padre': '06'},
  {'id': '062', 'nombre': 'Cardenal Caro', 'padre': '06'},
  {'id': '063', 'nombre': 'Colchagua', 'padre': '06'},
  {'id': '071', 'nombre': 'Talca', 'padre': '07'},
  {'id': '072', 'nombre': 'Cauquenes', 'padre': '07'},
  {'id': '073', 'nombre': 'Curicó', 'padre': '07'},
  {'id': '074', 'nombre': 'Linares', 'padre': '07'},
  {'id': '081', 'nombre': 'Concepción', 'padre': '08'},
  {'id': '082', 'nombre': 'Arauco', 'padre': '08'},
  {'id': '083', 'nombre': 'Biobío', 'padre': '08'},
  {'id': '091', 'nombre': 'Cautín', 'padre': '09'},
  {'id': '092', 'nombre': 'Malleco', 'padre': '09'},
  {'id': '101', 'nombre': 'Llanquihue', 'padre': '10'},
  {'id': '102', 'nombre': 'Chiloé', 'padre': '10'},
  {'id': '103', 'nombre': 'Osorno', 'padre': '10'},
  {'id': '104', 'nombre': 'Palena', 'padre': '10'},
  {'id': '111', 'nombre': 'Coyhaique', 'padre': '11'},
  {'id': '112', 'nombre': 'Aysén', 'padre': '11'},
  {'id': '113', 'nombre': 'Capitán Prat', 'padre': '11'},
  {'id': '114', 'nombre': 'General Carrera', 'padre': '11'},
  {'id': '121', 'nombre': 'Magallanes', 'padre': '12'},
  {'id': '122', 'nombre': 'Antártica Chilena', 'padre': '12'},
  {'id': '123', 'nombre': 'Tierra del Fuego', 'padre': '12'},
  {'id': '124', 'nombre': 'Última Esperanza', 'padre': '12'},
  {'id': '131', 'nombre': 'Santiago', 'padre': '13'},
  {'id': '132', 'nombre': 'Cordillera', 'padre': '13'},
  {'id': '133', 'nombre': 'Chacabuco', 'padre': '13'},
  {'id': '134', 'nombre': 'Maipo', 'padre': '13'},
  {'id': '135', 'nombre': 'Melipilla', 'padre': '13'},
  {'id': '136', 'nombre': 'Talagante', 'padre': '13'},
  {'id': '141', 'nombre': 'Valdivia', 'padre': '14'},
  {'id': '142', 'nombre': 'Ranco', 'padre': '14'},
  {'id': '151', 'nombre': 'Arica', 'padre': '15'},
  {'id': '152', 'nombre': 'Parinacota', 'padre': '15'},
  {'id': '161', 'nombre': 'Diguillín', 'padre': '16'},
  {'id': '162', 'nombre': 'Itata', 'padre': '16'},
  {'id': '163', 'nombre': 'Punilla', 'padre': '16'},
];
