/// Catálogo oficial localidades censales UY 2011.
const List<Map<String, String>> kUyNivel1 = <Map<String, String>>[
  {'id': '01', 'nombre': 'Montevideo'},
  {'id': '02', 'nombre': 'Artigas'},
  {'id': '03', 'nombre': 'Canelones'},
  {'id': '04', 'nombre': 'Cerro Largo'},
  {'id': '05', 'nombre': 'Colonia'},
  {'id': '06', 'nombre': 'Durazno'},
  {'id': '07', 'nombre': 'Flores'},
  {'id': '08', 'nombre': 'Florida'},
  {'id': '09', 'nombre': 'Lavalleja'},
  {'id': '10', 'nombre': 'Maldonado'},
  {'id': '11', 'nombre': 'Paysandu'},
  {'id': '12', 'nombre': 'Rio Negro'},
  {'id': '13', 'nombre': 'Rivera'},
  {'id': '14', 'nombre': 'Rocha'},
  {'id': '15', 'nombre': 'Salto'},
  {'id': '16', 'nombre': 'San Jose'},
  {'id': '17', 'nombre': 'Soriano'},
  {'id': '18', 'nombre': 'Tacuarembo'},
  {'id': '19', 'nombre': 'Treinta y Tres'},
];

const List<Map<String, String>> kUyNivel2 = <Map<String, String>>[
  {'id': '01', 'nombre': 'Montevideo', 'padre': '01'},
  {'id': '02', 'nombre': 'Artigas', 'padre': '02'},
  {'id': '03', 'nombre': 'Canelones', 'padre': '03'},
  {'id': '04', 'nombre': 'Cerro Largo', 'padre': '04'},
  {'id': '05', 'nombre': 'Colonia', 'padre': '05'},
  {'id': '06', 'nombre': 'Durazno', 'padre': '06'},
  {'id': '07', 'nombre': 'Flores', 'padre': '07'},
  {'id': '08', 'nombre': 'Florida', 'padre': '08'},
  {'id': '09', 'nombre': 'Lavalleja', 'padre': '09'},
  {'id': '10', 'nombre': 'Maldonado', 'padre': '10'},
  {'id': '11', 'nombre': 'Paysandu', 'padre': '11'},
  {'id': '12', 'nombre': 'Rio Negro', 'padre': '12'},
  {'id': '13', 'nombre': 'Rivera', 'padre': '13'},
  {'id': '14', 'nombre': 'Rocha', 'padre': '14'},
  {'id': '15', 'nombre': 'Salto', 'padre': '15'},
  {'id': '16', 'nombre': 'San Jose', 'padre': '16'},
  {'id': '17', 'nombre': 'Soriano', 'padre': '17'},
  {'id': '18', 'nombre': 'Tacuarembo', 'padre': '18'},
  {'id': '19', 'nombre': 'Treinta y Tres', 'padre': '19'},
];
