name: Deploy Functions Desa (manual)

on:
  workflow_dispatch:

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: "22"
          cache: npm
          cache-dependency-path: functions/package-lock.json

      - name: Install deps
        working-directory: functions
        run: npm ci --ignore-scripts

      - name: Deploy functions a puelo-desa
        uses: w9jds/firebase-action@5b73b1274a2229c7598af09e6e95addfb75f897b
        with:
          args: deploy --only functions --project puelo-desa
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PUELO_DESA }}
